services:
  - type: web
    name: wyx-cnn-digit-recognizer
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/web_server.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
